apiVersion: v1
kind: Service
metadata:
  name: pouring-puma-mychart
  labels:
    chart: "mychart-0.1.0"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: ubuntu-upstart
  selector:
    app: pouring-puma-mychart
